<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /* @var \Magento\Framework\View\Element\Template $block */ ?>
<?php /** @var $viewModel \Riverstone\TrackOrder\ViewModel\Data */
$viewModel = $block->getViewModel();
$helper = $viewModel->getDataHelper();
$_shipment = $block->getShipment();
?>
<?php
/* @var \Magento\Sales\Model\Order $_order */
$_order = $block->getOrder() ?>
<?php if ($_shipment && $_order): ?>
    <?php $trackCollection = $_shipment->getTracksCollection(); ?>
    <?php if ($trackCollection): ?>
        <br />
        <table class="shipment-track">
            <thead>
            <tr>
                <th><?= $block->escapeHtml(__('Shipped By')) ?></th>
                <th><?= $block->escapeHtml(__('Tracking Number')) ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($trackCollection as $_item):

                $trackUrl = $helper->getTrackingUrl($_item->getCarrierCode(), $_item->getNumber());
                ?>
                <tr>
                    <td><?= $block->escapeHtml($_item->getTitle()) ?>:</td>
                    <td>
                        <?php if ($trackUrl): ?>
                            <a href="<?= $block->escapeHtml($trackUrl); ?>" target="_blank">
                                <?= $block->escapeHtml($_item->getNumber()) ?>
                            </a>
                        <?php else:
                            $trackingUrl = $block->getTrackingUrl()->getUrl($_item);?>
                            <a href="<?= $block->escapeUrl($trackingUrl) ?>" target="_blank">
                                <?= $block->escapeHtml($_item->getNumber()) ?>
                            </a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach ?>
            </tbody>
        </table>
    <?php endif; ?>
<?php endif; ?>
